//------------------------------------------------------------------------------
// <auto-generated>
//     This code is generated by the tool.
//     Runtime version :4.0.30319.42000
//
//     Changes to this file may result in incorrect behavior, and these changes will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTCCSharpDemo.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly typed resource class for finding localized strings, etc.
    /// </summary>
    // Such is passed by StronglyTypedResourceBuilder class similar to ResGen
    // or Visual Studio tools automatically generated.
    // To add or remove members, edit the.resx file, then re-run ResGen(with /str as the command option),
    // or regenerate the VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Return the ResourceManager instance of the cache used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TRTCCSharpDemo.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Override the CurrentUICulture property of the current thread
        ///   Override the CurrentUICulture property of the current thread
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_normal {
            get {
                object obj = ResourceManager.GetObject("close_normal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap close_white {
            get {
                object obj = ResourceManager.GetObject("close_white", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_court {
            get {
                object obj = ResourceManager.GetObject("logo_court", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap logo_court_demo {
            get {
                object obj = ResourceManager.GetObject("logo_court_demo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MuteOff {
            get {
                object obj = ResourceManager.GetObject("MuteOff", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap MuteOn {
            get {
                object obj = ResourceManager.GetObject("MuteOn", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OpenFile {
            get {
                object obj = ResourceManager.GetObject("OpenFile", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Pause {
            get {
                object obj = ResourceManager.GetObject("Pause", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Play {
            get {
                object obj = ResourceManager.GetObject("Play", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpeedDown {
            get {
                object obj = ResourceManager.GetObject("SpeedDown", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap SpeedUp {
            get {
                object obj = ResourceManager.GetObject("SpeedUp", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Stop {
            get {
                object obj = ResourceManager.GetObject("Stop", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Find localized resources of type System.draw.icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon trtc {
            get {
                object obj = ResourceManager.GetObject("trtc", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
