//------------------------------------------------------------------------------
// <auto-generated>
//     This code generated by the tool.
//     Runtime version :4.0.30319.42000
//
//     Changes to this file may result in incorrect behavior, and these changes will be lost if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TRTCCSharpDemo.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "15.9.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
    }
}
